env:
  - GO111MODULE=on
builds:
  - id: buildGeneric
    main: ./cmd/ptemplate-form-handler
    binary: ptemplate-form-handler
    ldflags: -X github.com/nethruster/ptemplate-form-handler/internal.Version={{.Version}}
    goos:
      - darwin
      - windows
    goarch:
      - amd64

  - id: buildLinux
    main: ./cmd/ptemplate-form-handler
    binary: ptemplate-form-handler
    ldflags: -X github.com/nethruster/ptemplate-form-handler/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: archiveGeneric
    builds:
      - buildGeneric
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: macOS
    files:
      - examples/config.toml
      - LICENSE
      - README.md

  - id: archiveLinux
    builds:
      - buildLinux
    format: tar.gz
    files:
      - examples/config.toml
      - LICENSE
      - README.md
