env:
  - GO111MODULE=on
builds:
  - id: generic
    main: cmd/web-msg-handler/main.go
    binary: web-msg-handler
    ldflags: -X github.com/Miguel-Dorta/web-msg-handler/internal.Version={{.Version}}
    goos:
      - darwin
      - windows
    goarch:
      - amd64

  - id: linux
    main: cmd/web-msg-handler/main.go
    binary: web-msg-handler
    ldflags: -X github.com/Miguel-Dorta/web-msg-handler/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
archives:
  - id: archiveGeneric
    builds:
      - generic
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: macOS
    files:
      - examples/config.json
      - LICENSE
      - README.md

  - id: archiveLinux
    builds:
      - linux
    format: tar.gz
    files:
      - configs/systemd/web-msg-handler.service
      - examples/config.json
      - install.sh
      - LICENSE
      - README.md
