# Name you want the web to be called. This is used in the email subject: "Message from <web_name>".
web_name = "ptemplate.nethruster.com"
# Google's reCAPTCHA v2 secret key.
recaptcha_secret = "xkmBhVrYaB0NhtHpHgAWeTnLZpTSxCKs0gigByk5"

[mail]
# Mail you want to send the forms to.
mailto = "personal@gmail.com"
# Credentials of the account you want to send the mail.
username = "no-reply@nethruster.com"
password = "bNRxxIPxX7kLrbN8WCG22VUmpBqVBGgLTnyLdjob"
smtp_server = "smtp.nethruster.com"
port = 587
